#!/usr/bin/env bash

# Abort if it is not on a branch
if [[ $(git rev-parse --abbrev-ref HEAD) == "HEAD" ]]; then
  exit 0
fi

# Abort if a preivious commit message already exists
if (( $(grep -v "^#" "$1" | wc -l) > 1 )); then
  exit 0
fi

original=$(grep "^#" "$1")

pattern=.
if [ -e .gitattributes ]; then
  pattern=$(awk 'NF==0 {next} /^#.*/ {next} /linguist-generated=true/ {print ":^" $1}' < .gitattributes)
fi

chatgpt '' > $1 <<EOF
Generate a descriptive commit message summarising the following diff, following the Conventional Commits format.
$(git diff --name-status -- "$pattern")

\`\`\`diff
$(git diff --cached -- "$pattern" | head -n100)
\`\`\`
EOF

echo "$original" >> $1
