#!/bin/sh
original=$(cat $1)

pattern=.
if [ -e .gitattributes ]; then
  pattern=$(awk 'NF==0 {next} /^#.*/ {next} /linguist-generated=true/ {print ":^" $1}' < .gitattributes)
fi

# https://github.com/kardolus/chatgpt-cli
chatgpt 'Generate a terse but descriptive commit message from the following diff' \
  "$(git diff --cached -- "$pattern" | head -n100)" > $1

echo "$original" >> $1
