#!/usr/bin/env bash

git engage $1 || exit 1
branch=$(git ensure-suffix) || exit 1

# Rebase
git grapple || exit 1

if [ -e "$(git rev-parse --show-toplevel)/.git/REBASE_HEAD" ]; then
  echo "Aborting git ship for amendment."
  exit 0
fi

# Sanity check
if grep "fixup" <<< $(git log --format='%s' "$(git base)..HEAD") > /dev/null; then
  echo "There's a fixup commit! Aborting." >&2
  exit 1
fi

# Fast-forward to upstream
git push origin "$branch:$(git base | cut -d '/' -f 2)" || exit 1

# Remove branches
if [ "$branch" != "$(git suffix)" ]; then
  git engage && git branch -D "$branch" && git push origin --delete "$branch"
fi
